### ISSUE TITLE
Homework assignments for week 1 completed

### ISSUE THREAD

**Issue by kelseyeichbauer** [cven5873-ss23/website#1]
@larnsce

Do we need any special software installed on our computer for this course, or will everything be online?

**Comment by larnsce** [comment]
Hi @kelseyeichbauer, thank you for working through the assignment. 

From a software perspective, the only thing you need is a browser that's not the Internet Explorer (Chrome, Firefox, Arc, Safari, Edge all work).

Otherwise, we will use Posit Cloud infrastructure for our computing environment.

**Comment by larnsce** [comment]
Hi @kelseyeichbauer, I am sharing a reference to an issue of another participant to also inform you about the Posit Primers: https://github.com/cven5873-ss23/website/issues/4#issuecomment-1578032287
