### ISSUE TITLE
Homework assignments for week 1 completed

### ISSUE THREAD

**Issue by fredtusabe** [cven5873-ss23/website#10]

**Comment by larnsce** [comment]
Hi @fredtusabe. Thank you for submitting the homework. Please tag me using the `@` sign with my username larnsce in your comment for the next assignment.

**Comment by larnsce** [comment]
Before class tomorrow, pleaso sign in to the Posit Cloud with your GitHub account, and also setup the GitHub Personal Access Token.

https://cven5873-ss23.github.io/website/weeks/wk-01.html#join-the-course-workspace-on-posit-cloud

**Comment by fredtusabe** [comment]
@larnsce
