### ISSUE TITLE
Homework assignments for week 1 completed

### ISSUE THREAD

**Issue by Jemalibrahim** [cven5873-ss23/website#4]
@larnsce

**- Is there anything that I can practice on coding for the next week class? If so, what are those basic coding to which I will focus and get prepared?  
- If I missed the class in case for power cut or some challenge with internet, is there a possibility that I could get records or by what means that I can get the missed class? ** 
The learning goal, assignment and grading and other description about the course is very important and clear. The different topics will give basic understanding on data collection, analysis, data use and management.
From the data cycle, I hope will learn a lot about the whole process from defining the problem until analysis and visualization, Excel is powerful tool though I learned only the basics, so during spreadsheet data organization I will have the chance to investigate more on data organization. More advanced tools like R and others will give basic knowledge on data organization and analysis. 
As WASH professional, I am happy to see exercises related to waste management, sanitation and hope to see exercise related with water. I am happy to see also on contents the different programs like R, RStudio IDE, Git, GitHub, tidy verse, Quarto, to some of them I heard nothing and to some others only little. Data communication using different publishing systems is also very interesting for organizing papers to be published.
Thanks

**Comment by larnsce** [comment]
Hi @Jemalibrahim, thank you for working through the assignment.

> Is there anything that I can practice on coding for the next week class? If so, what are those basic coding to which I will focus and get prepared?

I don't expect any prior knowledge in R or programming for the class, but if you are motivated to start learning, then I would recommend looking at the primers that are accessible on posit.cloud. They are interactive tutorials that let you practice writing R code with hints and solutions provided:

https://posit.cloud/learn/primers

> If I missed the class in case for power cut or some challenge with internet, is there a possibility that I could get records or by what means that I can get the missed class?

Yes, I am going to record the classes, but please do let me know when you anticipate that you may not be able to join a class. I do hope that you will be able to participate in the live session. 

I am glad to see that you find the content of the course suitable and hope your expectations will be fulfilled.

**Comment by larnsce** [comment]
I am going to close the issue to mark it as "done".

**Comment by Jemalibrahim** [comment]
Thank you very much for the quick response.
