### ISSUE TITLE
Homework assignments for week 1 completed

### ISSUE THREAD

**Issue by Noelumukunzi** [cven5873-ss23/website#5]
@larnsce 
I would like to ask if there is  other mean to help a student with zero knowledge about progrmming or if the course itself is enough for student who doesn't have coding knowledge?

**Comment by larnsce** [comment]
Hi @Noelumukunzi, thanks for working through the assignment. The course itself is developed for novice users to R and programming in general. 

During the course, you will receive additional resources that will support you in continuing your learning journey.

While I do not expect you to practice any coding prior to our first lecture, there was question about that here: #4.

**Comment by larnsce** [comment]
I am going to close this issue to mark it as "done".

**Comment by Noelumukunzi** [comment]
Thank you for information and clarifying.

kind regards,
Noel.
________________________________
