### ISSUE TITLE
Homework assignments for week 1 completed

### ISSUE THREAD

**Issue by ClaudiaN11** [cven5873-ss23/website#6]
@larnsce Will this course cover the utilization of satellite imagery and remote sensing technologies as data sources for monitoring air quality trends, assessing the long-range transport of pollutants, and evaluating air pollution in areas without ground-based monitoring stations?
 Thank you so much

**Comment by ClaudiaN11** [comment]
Hello, @larnsce I am signed up on Canvas page for this course. please let me know you can't still find my name on the student roster. 
Thank you

**Comment by ClaudiaN11** [comment]
@larnsce ;I have a different name on Canvas "NANKAFU BAAMBA CLAUDINE"

**Comment by larnsce** [comment]
I apologise, and thank you for clarifying.

**Comment by ClaudiaN11** [comment]
@larnsce, thank you Sir.
