### ISSUE TITLE
Homework assignments for week 1 completed

### ISSUE THREAD

**Issue by imuhanda** [cven5873-ss23/website#7]
@larnsce,
I am taking all possible time to explore data science tools, Quarto file format and the RStudio IDE visual editing mode. They are mostly new things for me. However, with time and practice I hope to acquire more about them and master them.

**Comment by larnsce** [comment]
@imuhanda, thanks for working through the assignment. Yes, we will introduce a wide range of tools, and it's okay if all of them are new to you.
