### ISSUE TITLE
Hello, 

### ISSUE THREAD

**Issue by Jemalibrahim** [cven5873-ss23/website#8]
This is Jemal. I am happy to be here to learn from you. Thank you.

**Comment by larnsce** [comment]
Hi @Jemalibrahi . Thank you for submitting the homework. Please tag me using the `@` sign with my username larnsce in your comment for the next assignment.

**Comment by Jemalibrahim** [comment]
Thank you, I will do that.

**Comment by Jemalibrahim** [comment]
Hello @larnsce. I hope i have done that yesterday
