### ISSUE TITLE
homework assignments for week 1 completed.

### ISSUE THREAD

**Issue by icebergh** [cven5873-ss23/website#9]
@larnsce a few questions regarding the course overview:

1. Are these the right links for the class texts? 
https://r4ds.hadley.nz/ 
https://jhudatascience.org/tidyversecourse/index.html

2. I see that there are some student hours posted on Thursdays from 10:00 a.m. - 12:00 p.m. CEST on zoom. Since I'm located in Cincinnati on EDT, I believe this would be 4:00 - 6:00 a.m. for me, which is going to be rather difficult for my full participation. I'm wondering if additional hours could be added a bit later in the day?

3. My wife and I are expecting the birth of our second child this summer (approximately July 1). It's possible that I will miss the lecture on July 3, and depending on unforeseen circumstances, I may need some extra time for assignment(s) during my parental leave. I will communicate with the professor if circumstances arise that may interfere with my timely completion of the assignments. Will the lectures be recorded for me to review them in case I miss one?

I'm looking forward to the course, I'm not very comfortable with programming and I've never used R, so I think I will be learning a lot!

**Comment by icebergh** [comment]
@larnsce I saw your responses to other students about Posit Primers, thanks! 

Also, regarding the browsers, I typically use the Brave browser, but I can switch to Chrome during the course, if that would be better?

**Comment by larnsce** [comment]
Hi @icebergh, thank you for working through the assignment.

1. yes
2. yes, we can figure something out. I suggest we book a time in the calendar when you want to chat to me.
3. that's wonderful and exciting. Definitely. I will record the lectures and if you let me know that you will be late on an assignment, then you will get an extension.
4. Brave browser should be fine, as it's based on Chromium. 

> I'm looking forward to the course, I'm not very comfortable with programming and I've never used R, so I think I will be learning a lot!

That's great! No prior programming knowledge is expected.

I am closing the comment to mark this task as "done".
